import { ENROLLMENT_STATUS } from "./status.js";


export const ALLOWED_ENROLLMENT_TRANSITIONS = {
  [ENROLLMENT_STATUS.PENDING]: [ENROLLMENT_STATUS.ENROLLED],
  [ENROLLMENT_STATUS.ENROLLED]: [],
  [ENROLLMENT_STATUS.CANCELLED]: [],
  [ENROLLMENT_STATUS.EXPIRED]: [],
};
